### ISSUE TITLE
How do I install it on my TempleOS?

### ISSUE THREAD

**Issue by amxrmxhdx** [Rion96/GKey#3]
Hey, I have TempleOS as a VMWare VM, how do I install GKey?

**Comment by Rion96** [comment]
Download GKey.ISO from [here](https://github.com/Rion96/GKey/releases/tag/v3.0) and mount it in VMware. Once you're booted up, run the following commands in TempleOS, as outlined in my readme:
`Cd("T:");`
`#include "Setup.HC.Z";`

That should do the trick. If you have any further questions, feel free to ask :)

**Comment by amxrmxhdx** [comment]
Danke man :D

**Comment by Rion96** [comment]
Kein Problem :)

**Comment by amxrmxhdx** [comment]
![image](https://user-images.githubusercontent.com/29169021/83299363-4f23e280-a1f6-11ea-80e8-9224434ec9a7.png)
For some reason it's telling me that the file doesn't exist :/

**Comment by Rion96** [comment]
`T:` should be the drive the ISO mounts to. These look to be the contents of a TempleOS ISO instead. Are you sure you have the my ISO mounted and not the TempleOS one? Maybe also make sure that your VM doesn't have multiple CD drives with multiple ISOs or something. I'm not very familiar with VMware, so I'm afraid I can't help you much with the details there 😅

**Comment by amxrmxhdx** [comment]
Which VM do you use?

**Comment by Rion96** [comment]
I use VirtualBox, but TempleOS really should work fine with VMware too. You'd also lose PC speaker support in VirtualBox, so VMware is probably the better choice :)

**Comment by amxrmxhdx** [comment]
How do I do it on VirtualBox? Use it as primary or secundary master?

**Comment by Rion96** [comment]
Secondary Master for the CD drive. Primary Master for the hard drive you have TempleOS installed to. That's how it's configured for me.
