### ISSUE TITLE
ISO doesn't work for me.

### ISSUE THREAD

**Issue by YxNiI** [Rion96/GKey#4]
Hello Rion96,
I am sorry but I did not find a way to use direct messages in GitHub and wanted to ask you something about the installation of GKey.
I really hope this is ok.
Anyway, here is my question/problem:

I am unsure how to exactly install GKey; as far as I understood, I am supposed to use the ISO you provided as an alternative TempleOS.ISO,install it that way and afterwards I am supposed to use the commands you showed in the readme-section,  to install GKey.
Problem is the ISOs won't work for me, I tried them all and I tried in the free WMware-version and in VirtualBox.
Or do I have to find a way to transfer the GKey-files into a regular TempleOS installation? Which seems very difficult to me,
I only saw a way with paid WMware if I remember correctly.

I would really appreciate some help, because having to memorize two keyboard layouts can get quite taxing after some time and I would really like to use GKey.

Have a good day!

**Comment by Rion96** [comment]
If I understood correctly, you believe that I am distributing an altered copy of TempleOS? Then I'm afraid you're mistaken. The ISO I provide merely contains the HomeKeyPlugins.HC.Z file needed to change the keyboard layout and font as well as a small setup script you can use to copy it into the right place for you. I don't use VMWare, so I can't speak in detail about it. I use VirtualBox. The course of action should roughly be the following:

1. Get the most recent ISO for TempleOS.
2. Create a virtual machine with an IDE CD and HDD. In VirtualBox this is done automatically when you select "Other/Unknown (64-bit) as the operating system for the virtual machine.
3. Start the Machine with the TempleOS ISO.
4. Install TempleOS to the hard drive by following the on screen instructions.
5. Remove the TempleOS ISO from the virtual machine and insert my ISO "GKey.ISO"
6. Restart the virtual machine.
7. You should see "TempleOS Boot Loader"
8. Select Option 1 (Drive C).
9. Once booted up, decline to take the tour and follow my readme instructions from there:

```
Cd("T:");
#include "Setup.HC.Z";
```

Hope this clears things up :)

**Comment by YxNiI** [comment]
Oh my god, thank you so much!
I didn't realize you could insert the Gkey.ISO into the already installed TempleOS and then use the commands you specified.
Now I can finally use a German keyboard-layout, thank you. :D

**Comment by Rion96** [comment]
You're welcome! Have fun :)
